version: '3.8'
name: zenergy

#  Create Network for DB
networks:
    zenergy-network:
        name: zenergy-network
        driver: bridge

# Z-Energy Database Volume
volumes:
    zenergy:
        name: zenergy-volume

#  Web Service
services:
    # Next JS Web Service
    web:
        container_name: web
        depends_on:
            - mongo
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - zenergy-network
        ports:
            - 3000:3000
        volumes:
            - ./src:/zenergy/src

    # # MongoDB Service

    mongo:
        image: mongo
        container_name: mongo
        ports:
            - 27017:27017
        networks:
            - zenergy-network
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DB=${MONGO_INITDB_DB}
            - MONGODB_URI_ROOT=${MONGODB_URI_ROOT}
            - MONGODB_URI_ADMIN=${MONGODB_URI_ADMIN}
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASS=${MONGO_PASS}
        volumes:
            - 'zenergy:/data/db'
            # If there's no volume uncomment the next line. This script will create a admin user and add initial data to the DB
            - './bash/mongoinit.sh/:/docker-entrypoint-initdb.d/mongoinit.sh:ro'
